### ISSUE TITLE
执行`convert`时出现 IO 错误

### ISSUE THREAD

**Issue by KezhiAdore** [cncases/cases#1]
执行`convert`命令时，运行一段世界后报错：
```shell
2024-01-19T11:57:18.865094Z  INFO convert: inserting 15324160, time: 875
2024-01-19T11:57:18.937344Z  INFO convert: inserting 15325184, time: 875
2024-01-19T11:57:19.012542Z  INFO convert: inserting 15326208, time: 876
2024-01-19T11:57:19.128853Z  INFO convert: inserting 15327232, time: 876
2024-01-19T11:57:19.198966Z  INFO convert: inserting 15328256, time: 876
2024-01-19T11:57:19.267122Z  INFO convert: inserting 15329280, time: 876
2024-01-19T11:57:19.390479Z  INFO convert: inserting 15330304, time: 876
thread 'main' panicked at src/bin/convert.rs:61:45:
called `Result::unwrap()` on an `Err` value: Error { message: "IO error: While open a file for appending: /data/cases/rocksdb/002043.log: Too many open files" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
系统信息：
```shell
$ uname -a 
Linux ubuntu 5.15.0-84-generic #93-Ubuntu SMP Tue Sep 5 17:16:10 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
$ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-m: resident set size (kbytes)      unlimited
-u: processes                       124695
-n: file descriptors                1024
-l: locked-in-memory size (kbytes)  4005456
-v: address space (kbytes)          unlimited
-x: file locks                      unlimited
-i: pending signals                 124695
-q: bytes in POSIX msg queues       819200
-e: max nice                        0
-r: max rt priority                 0
-N 15:                              unlimited
```
重新执行之后运行到同样的地方报同样的错误，看起来时文件打开限制的问题，有什么解决办法嘛？

**Comment by cncases** [comment]
如果是 Linux，试试 `ulimit -n 10000`

**Comment by KezhiAdore** [comment]
执行`ulimit -n 10000`修改文件描述符大小后重新运行`convert`，转换正常。
问题已解决

**Comment by BenLin0** [comment]
"convert" 是什么命令？我得到：

Command 'convert' not found, but can be installed with:
sudo apt install graphicsmagick-imagemagick-compat  # version 1.4+really1.3.38-1ubuntu0.1, or
sudo apt install imagemagick-6.q16                  # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3
sudo apt install imagemagick-6.q16hdri              # version 8:6.9.11.60+dfsg-1.3ubuntu0.22.04.3

我没看到跟导入数据相关的代码。

**Comment by cncases** [comment]
@BenLin0 https://github.com/cncases/cases/releases

**Comment by BenLin0** [comment]
zip里看到了3个可执行文件 convert main index. 它们是从这个 github repo 的源代码里编译出来的吗？我应该如何编译呢？

（用源代码我比较放心；给我可执行文件我不敢用）

**Comment by BenLin0** [comment]
@cncases 谢谢增加了编译的介绍。现在编译已经成功，开始 convert
在我的干净ubuntu22.04上，需要增加一个操作才编译成功：
sudo apt-get install clang

然后编译，就可以
target/release/convert config.toml
(location 等都已经如reame一样设置好)

**Comment by BenLin0** [comment]
好慢啊，index 足足跑了一个星期了，不知道什么时候会结束

2024-01-27T17:44:08.859373Z  INFO index: 33034000 done, 438993
2024-01-27T17:44:25.275684Z  INFO index: 33035000 done, 439009
2024-01-27T17:44:37.735553Z  INFO index: 33036000 done, 439022

**Comment by cncases** [comment]
@BenLin0 你电脑配置太低了吧，我加全文都没那么慢……

**Comment by BenLin0** [comment]
> @BenLin0 你电脑配置太低了吧，我加全文都没那么慢……

是我的硬盘太慢了；主硬盘快，但是有点小，所以我安排在副硬盘上；昨天终于把进程杀了，转移到主硬盘上跑， index大概跑了6小时，仅是标题，现在网站能工作了。

谢谢！
