### ISSUE TITLE
运行`main`出错：Too many open files

### ISSUE THREAD

**Issue by KezhiAdore** [cncases/cases#3]
直接运行`./main`命令行结果如下：
```shell
$ ./main
2024-01-22T06:56:34.400725Z  INFO main: listening on http://127.0.0.1:8081
```
但访问8081端口无任何响应。
使用管理员权限运行`./main`结果如下：
```shell
$ sudo ./main2024-01-22T06:56:38.123740Z  INFO main: listening on http://127.0.0.1:8081
thread 'main' panicked at src/bin/main.rs:27:84:
called `Result::unwrap()` on an `Err` value: Error { message: "IO error: While open a file for random read: /data/cases/rocksdb/009237.sst: Too many open files" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    19883 IOT instruction  sudo ./main
```
1. 该服务运行是否必须使用超级管理员权限，可否在非管理员下运行？
2. 如何解决上述报错？

**Comment by cncases** [comment]
在大多数操作系统中，都有一个限制，即同时能打开的文件数量有一个上限，这个上限包括每个进程的限制和整个系统的限制。您可以增加这个限制。

在类 Unix 系统上，您可以使用 ulimit -n 命令查看当前的限制，并且可以使用 ulimit -n [新的限制] 为当前会话设置更高的限制。

作为一个更持久的解决方案，您可以编辑 /etc/security/limits.conf（或者根据您的系统可能是类似的文件）来增加限制。

要编辑 /etc/security/limits.conf 文件以永久增加文件描述符的限制，请按照以下步骤操作：

以超级用户身份打开文件:

在终端中输入以下命令来以超级用户（通常是 root 用户）身份编辑该文件：

 ```bash
sudo nano /etc/security/limits.conf
```
这里使用了 nano 作为文本编辑器，但您也可以使用任何您熟悉的编辑器，如 vi 或 vim。

编辑或添加条目:

在文件的末尾，您可以添加或编辑条目来设置所需的限制。格式如下：

`<domain> <type> <item> <value>`

例如，要将所有用户的打开文件数量限制设置为 10240，可以添加以下行：

```markdown

    * soft nofile 10240
    * hard nofile 10240
```

其中 * 表示此设置适用于所有用户，soft 和 hard 分别代表软限制和硬限制（软限制可以由用户增加，硬限制不可更改），nofile 表示打开文件的数量，10240 是新的限制值。

保存并关闭文件:

添加必要的行后，保存并关闭文件。

使更改生效:

要使这些更改生效，您可能需要重启系统或至少注销再重新登录。

验证新的限制:

重启后，可以用以下命令验证新的限制是否生效：

```bash
ulimit -n
```

根据需要调整:

如果您发现新的限制不够或过高，可以再次通过编辑 limits.conf 文件进行调整。

请注意，设置过高的限制可能会影响系统稳定性，因此根据系统的能力和需求找到平衡非常重要。

**Comment by cncases** [comment]
/chatgpt 如何解决 Too many open files 错误
